"""도메인 모델 초기 스키마

Revision ID: 0002_domain_model
Revises: 0001_enable_pg_trgm
Create Date: 2026-08-01 00:04:55.713385
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_domain_model"
down_revision: str | None = "0001_enable_pg_trgm"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_seeded", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["category.id"],
            name=op.f("fk_category_parent_id_category"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
    )
    op.create_index(op.f("ix_category_user_id"), "category", ["user_id"], unique=False)
    op.create_index(
        "ix_category_user_id_parent_id", "category", ["user_id", "parent_id"], unique=False
    )
    op.create_index(
        "uq_category_user_id_parent_id_name",
        "category",
        ["user_id", "parent_id", "name"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_table(
        "producer",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("region", sa.String(length=120), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_producer")),
        sa.UniqueConstraint("user_id", "name", name="uq_producer_user_id_name"),
    )
    op.create_index(op.f("ix_producer_user_id"), "producer", ["user_id"], unique=False)
    op.create_table(
        "variety",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_variety")),
        sa.UniqueConstraint("user_id", "name", name="uq_variety_user_id_name"),
    )
    op.create_index(op.f("ix_variety_user_id"), "variety", ["user_id"], unique=False)
    op.create_table(
        "vendor",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "mart",
                "online",
                "duty_free",
                "bottle_shop",
                "bar",
                "brewery",
                "event",
                "gift",
                "other",
                name="vendor_kind",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor")),
        sa.UniqueConstraint("user_id", "name", name="uq_vendor_user_id_name"),
    )
    op.create_index(op.f("ix_vendor_user_id"), "vendor", ["user_id"], unique=False)
    op.create_table(
        "product",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("name_en", sa.String(length=300), nullable=True),
        sa.Column("normalized_name", sa.String(length=300), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("producer_id", sa.UUID(), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("region", sa.String(length=120), nullable=True),
        sa.Column("abv", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("vintage", sa.Integer(), nullable=True),
        sa.Column("age_years", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("personal_rating", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("import_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "abv IS NULL OR (abv >= 0 AND abv <= 100)", name=op.f("ck_product_abv_range")
        ),
        sa.CheckConstraint(
            "age_years IS NULL OR age_years >= 0", name=op.f("ck_product_age_years_non_negative")
        ),
        sa.CheckConstraint(
            "personal_rating IS NULL OR (personal_rating > 0 AND personal_rating <= 6)",
            name=op.f("ck_product_personal_rating_range"),
        ),
        sa.CheckConstraint(
            "vintage IS NULL OR (vintage BETWEEN 1800 AND 2200)",
            name=op.f("ck_product_vintage_range"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_product_category_id_category"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producer.id"],
            name=op.f("fk_product_producer_id_producer"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
    )
    op.create_index(
        "ix_product_name_trgm",
        "product",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_product_user_id"), "product", ["user_id"], unique=False)
    op.create_index(
        "ix_product_user_id_deleted_at_category_id",
        "product",
        ["user_id", "deleted_at", "category_id"],
        unique=False,
    )
    op.create_index(
        "uq_product_identity",
        "product",
        ["user_id", "normalized_name", "vintage", "abv"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_table(
        "product_variety",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("variety_id", sa.UUID(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_product_variety_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variety_id"],
            ["variety.id"],
            name=op.f("fk_product_variety_variety_id_variety"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variety")),
        sa.UniqueConstraint(
            "product_id", "variety_id", name="uq_product_variety_product_id_variety_id"
        ),
    )
    op.create_index(
        op.f("ix_product_variety_user_id"), "product_variety", ["user_id"], unique=False
    )
    op.create_table(
        "sku",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("volume_ml", sa.Integer(), nullable=False),
        sa.Column("barcode", sa.String(length=64), nullable=True),
        sa.Column(
            "barcode_type",
            sa.Enum(
                "ean13",
                "upca",
                "ean8",
                "rcn",
                "other",
                name="barcode_type",
                native_enum=False,
                length=24,
            ),
            nullable=True,
        ),
        sa.Column("package_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("volume_ml > 0", name=op.f("ck_sku_volume_positive")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_sku_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sku")),
        sa.UniqueConstraint("product_id", "volume_ml", name="uq_sku_product_id_volume_ml"),
    )
    op.create_index(op.f("ix_sku_user_id"), "sku", ["user_id"], unique=False)
    op.create_index(
        "uq_sku_user_id_barcode",
        "sku",
        ["user_id", "barcode"],
        unique=True,
        postgresql_where="barcode IS NOT NULL AND deleted_at IS NULL",
    )
    op.create_table(
        "purchase",
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=True),
        sa.Column("purchased_on", sa.Date(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_list_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("unit_paid_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("fx_rate", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("foreign_unit_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("discount_note", sa.Text(), nullable=True),
        sa.Column("import_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "char_length(currency) = 3", name=op.f("ck_purchase_currency_is_iso4217")
        ),
        sa.CheckConstraint(
            "foreign_unit_price IS NULL OR fx_rate IS NOT NULL",
            name=op.f("ck_purchase_foreign_price_needs_fx_rate"),
        ),
        sa.CheckConstraint(
            "fx_rate IS NULL OR fx_rate > 0", name=op.f("ck_purchase_fx_rate_positive")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_purchase_quantity_positive")),
        sa.CheckConstraint(
            "unit_list_price IS NULL OR unit_list_price >= 0",
            name=op.f("ck_purchase_unit_list_price_non_negative"),
        ),
        sa.CheckConstraint(
            "unit_paid_price IS NULL OR unit_paid_price >= 0",
            name=op.f("ck_purchase_unit_paid_price_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["sku.id"], name=op.f("fk_purchase_sku_id_sku"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.id"],
            name=op.f("fk_purchase_vendor_id_vendor"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase")),
    )
    op.create_index("ix_purchase_sku_id", "purchase", ["sku_id"], unique=False)
    op.create_index(op.f("ix_purchase_user_id"), "purchase", ["user_id"], unique=False)
    op.create_index(
        "ix_purchase_user_id_purchased_on", "purchase", ["user_id", "purchased_on"], unique=False
    )
    op.create_table(
        "bottle",
        sa.Column("purchase_id", sa.UUID(), nullable=False),
        sa.Column("label_no", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "unopened",
                "open",
                "finished",
                "gifted",
                "sold",
                name="bottle_status",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("opened_on", sa.Date(), nullable=True),
        sa.Column("finished_on", sa.Date(), nullable=True),
        sa.Column("remaining_ml", sa.Integer(), nullable=True),
        sa.Column("storage_location", sa.String(length=200), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status <> 'finished' OR remaining_ml = 0",
            name=op.f("ck_bottle_finished_has_zero_remaining"),
        ),
        sa.CheckConstraint(
            "status <> 'unopened' OR opened_on IS NULL",
            name=op.f("ck_bottle_unopened_has_no_opened_on"),
        ),
        sa.CheckConstraint("label_no > 0", name=op.f("ck_bottle_label_no_positive")),
        sa.CheckConstraint(
            "opened_on IS NULL OR finished_on IS NULL OR finished_on >= opened_on",
            name=op.f("ck_bottle_finished_after_opened"),
        ),
        sa.CheckConstraint(
            "remaining_ml IS NULL OR remaining_ml >= 0",
            name=op.f("ck_bottle_remaining_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchase.id"],
            name=op.f("fk_bottle_purchase_id_purchase"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bottle")),
        sa.UniqueConstraint("purchase_id", "label_no", name="uq_bottle_purchase_id_label_no"),
    )
    op.create_index(
        "ix_bottle_purchase_id_status", "bottle", ["purchase_id", "status"], unique=False
    )
    op.create_index(op.f("ix_bottle_user_id"), "bottle", ["user_id"], unique=False)
    op.create_index("ix_bottle_user_id_status", "bottle", ["user_id", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bottle_user_id_status", table_name="bottle")
    op.drop_index(op.f("ix_bottle_user_id"), table_name="bottle")
    op.drop_index("ix_bottle_purchase_id_status", table_name="bottle")
    op.drop_table("bottle")
    op.drop_index("ix_purchase_user_id_purchased_on", table_name="purchase")
    op.drop_index(op.f("ix_purchase_user_id"), table_name="purchase")
    op.drop_index("ix_purchase_sku_id", table_name="purchase")
    op.drop_table("purchase")
    op.drop_index(
        "uq_sku_user_id_barcode",
        table_name="sku",
        postgresql_where="barcode IS NOT NULL AND deleted_at IS NULL",
    )
    op.drop_index(op.f("ix_sku_user_id"), table_name="sku")
    op.drop_table("sku")
    op.drop_index(op.f("ix_product_variety_user_id"), table_name="product_variety")
    op.drop_table("product_variety")
    op.drop_index(
        "uq_product_identity", table_name="product", postgresql_where="deleted_at IS NULL"
    )
    op.drop_index("ix_product_user_id_deleted_at_category_id", table_name="product")
    op.drop_index(op.f("ix_product_user_id"), table_name="product")
    op.drop_index(
        "ix_product_name_trgm",
        table_name="product",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("product")
    op.drop_index(op.f("ix_vendor_user_id"), table_name="vendor")
    op.drop_table("vendor")
    op.drop_index(op.f("ix_variety_user_id"), table_name="variety")
    op.drop_table("variety")
    op.drop_index(op.f("ix_producer_user_id"), table_name="producer")
    op.drop_table("producer")
    op.drop_index(
        "uq_category_user_id_parent_id_name",
        table_name="category",
        postgresql_where="deleted_at IS NULL",
    )
    op.drop_index("ix_category_user_id_parent_id", table_name="category")
    op.drop_index(op.f("ix_category_user_id"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
