"""시음 세션과 첨부 파일

Revision ID: 0004_tasting
Revises: 0003_auth
Create Date: 2026-08-01 08:00:53.212134
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_tasting"
down_revision: str | None = "0003_auth"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasting_session",
        sa.Column("bottle_id", sa.UUID(), nullable=True),
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("tasted_on", sa.Date(), nullable=False),
        sa.Column("poured_ml", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("nose", sa.Text(), nullable=True),
        sa.Column("palate", sa.Text(), nullable=True),
        sa.Column("finish", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("place", sa.String(length=200), nullable=True),
        sa.Column("companions", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "poured_ml IS NULL OR poured_ml > 0", name=op.f("ck_tasting_session_poured_ml_positive")
        ),
        sa.CheckConstraint(
            "rating IS NULL OR (rating >= 0 AND rating <= 6.0 AND (rating * "
            "2) = floor(rating * 2))",
            name=op.f("ck_tasting_session_rating_half_step_within_range"),
        ),
        sa.ForeignKeyConstraint(
            ["bottle_id"],
            ["bottle.id"],
            name=op.f("fk_tasting_session_bottle_id_bottle"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["sku.id"], name=op.f("fk_tasting_session_sku_id_sku"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasting_session")),
    )
    op.create_index(
        "ix_tasting_session_bottle_id_tasted_on",
        "tasting_session",
        ["bottle_id", "tasted_on"],
        unique=False,
    )
    op.create_index(
        "ix_tasting_session_sku_id_tasted_on",
        "tasting_session",
        ["sku_id", "tasted_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tasting_session_user_id"), "tasting_session", ["user_id"], unique=False
    )
    op.create_index(
        "ix_tasting_session_user_id_tasted_on",
        "tasting_session",
        ["user_id", "tasted_on"],
        unique=False,
    )
    op.create_table(
        "attachment",
        sa.Column(
            "kind",
            sa.Enum(
                "label",
                "tasting",
                "bottle",
                "other",
                name="attachment_kind",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=300), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("bottle_id", sa.UUID(), nullable=True),
        sa.Column("tasting_session_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(product_id IS NOT NULL)::int + (bottle_id IS NOT NULL)::int + "
            "(tasting_session_id IS NOT NULL)::int = 1",
            name=op.f("ck_attachment_attachment_has_exactly_one_owner"),
        ),
        sa.CheckConstraint("byte_size > 0", name=op.f("ck_attachment_byte_size_positive")),
        sa.ForeignKeyConstraint(
            ["bottle_id"],
            ["bottle.id"],
            name=op.f("fk_attachment_bottle_id_bottle"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_attachment_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tasting_session_id"],
            ["tasting_session.id"],
            name=op.f("fk_attachment_tasting_session_id_tasting_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachment")),
        sa.UniqueConstraint("user_id", "sha256", "kind", name="uq_attachment_user_sha256_kind"),
    )
    op.create_index("ix_attachment_bottle_id", "attachment", ["bottle_id"], unique=False)
    op.create_index("ix_attachment_product_id", "attachment", ["product_id"], unique=False)
    op.create_index(
        "ix_attachment_tasting_session_id", "attachment", ["tasting_session_id"], unique=False
    )
    op.create_index(op.f("ix_attachment_user_id"), "attachment", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attachment_user_id"), table_name="attachment")
    op.drop_index("ix_attachment_tasting_session_id", table_name="attachment")
    op.drop_index("ix_attachment_product_id", table_name="attachment")
    op.drop_index("ix_attachment_bottle_id", table_name="attachment")
    op.drop_table("attachment")
    op.drop_index("ix_tasting_session_user_id_tasted_on", table_name="tasting_session")
    op.drop_index(op.f("ix_tasting_session_user_id"), table_name="tasting_session")
    op.drop_index("ix_tasting_session_sku_id_tasted_on", table_name="tasting_session")
    op.drop_index("ix_tasting_session_bottle_id_tasted_on", table_name="tasting_session")
    op.drop_table("tasting_session")
    # ### end Alembic commands ###
