"""offline_sync

Revision ID: 0005_offline_sync
Revises: 0004_tasting
Create Date: 2026-08-01 19:58:27.659246
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005_offline_sync"
down_revision: str | None = "0004_tasting"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conflict_log",
        sa.Column("entity", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("server_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("client_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("client_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_key", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conflict_log")),
    )
    op.create_index(op.f("ix_conflict_log_user_id"), "conflict_log", ["user_id"], unique=False)
    op.create_index(
        "ix_conflict_log_user_id_entity_id", "conflict_log", ["user_id", "entity_id"], unique=False
    )
    op.create_index(
        "ix_conflict_log_user_id_updated_at",
        "conflict_log",
        ["user_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "outbox_receipt",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("entity", sa.String(length=40), nullable=False),
        sa.Column("operation", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("response_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_receipt")),
    )
    op.create_index(op.f("ix_outbox_receipt_user_id"), "outbox_receipt", ["user_id"], unique=False)
    op.create_index(
        "ix_outbox_receipt_user_id_created_at",
        "outbox_receipt",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "sync_cursor",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("cursor", sa.Text(), nullable=False),
        sa.Column("pulled_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_sync_cursor")),
    )
    op.create_index(
        "ix_attachment_user_id_updated_at", "attachment", ["user_id", "updated_at"], unique=False
    )
    op.create_index(
        "ix_bottle_user_id_updated_at", "bottle", ["user_id", "updated_at"], unique=False
    )
    op.create_index(
        "ix_category_user_id_updated_at", "category", ["user_id", "updated_at"], unique=False
    )
    op.create_index(
        "ix_producer_user_id_updated_at", "producer", ["user_id", "updated_at"], unique=False
    )
    op.create_index(
        "ix_product_user_id_updated_at", "product", ["user_id", "updated_at"], unique=False
    )
    op.create_index(
        "ix_product_variety_user_id_updated_at",
        "product_variety",
        ["user_id", "updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_purchase_user_id_updated_at", "purchase", ["user_id", "updated_at"], unique=False
    )
    op.create_index("ix_sku_user_id_updated_at", "sku", ["user_id", "updated_at"], unique=False)
    op.create_index(
        "ix_tasting_session_user_id_updated_at",
        "tasting_session",
        ["user_id", "updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_variety_user_id_updated_at", "variety", ["user_id", "updated_at"], unique=False
    )
    op.create_index(
        "ix_vendor_user_id_updated_at", "vendor", ["user_id", "updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vendor_user_id_updated_at", table_name="vendor")
    op.drop_index("ix_variety_user_id_updated_at", table_name="variety")
    op.drop_index("ix_tasting_session_user_id_updated_at", table_name="tasting_session")
    op.drop_index("ix_sku_user_id_updated_at", table_name="sku")
    op.drop_index("ix_purchase_user_id_updated_at", table_name="purchase")
    op.drop_index("ix_product_variety_user_id_updated_at", table_name="product_variety")
    op.drop_index("ix_product_user_id_updated_at", table_name="product")
    op.drop_index("ix_producer_user_id_updated_at", table_name="producer")
    op.drop_index("ix_category_user_id_updated_at", table_name="category")
    op.drop_index("ix_bottle_user_id_updated_at", table_name="bottle")
    op.drop_index("ix_attachment_user_id_updated_at", table_name="attachment")
    op.drop_table("sync_cursor")
    op.drop_index("ix_outbox_receipt_user_id_created_at", table_name="outbox_receipt")
    op.drop_index(op.f("ix_outbox_receipt_user_id"), table_name="outbox_receipt")
    op.drop_table("outbox_receipt")
    op.drop_index("ix_conflict_log_user_id_updated_at", table_name="conflict_log")
    op.drop_index("ix_conflict_log_user_id_entity_id", table_name="conflict_log")
    op.drop_index(op.f("ix_conflict_log_user_id"), table_name="conflict_log")
    op.drop_table("conflict_log")
    # ### end Alembic commands ###
