"""llm_settings

Revision ID: 0006_llm_settings
Revises: 0005_offline_sync
Create Date: 2026-08-02 11:05:38.448540
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006_llm_settings"
down_revision: str | None = "0005_offline_sync"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_setting",
        sa.Column(
            "provider",
            sa.Enum("openai", name="llm_provider", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("api_key_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("api_key_hint", sa.String(length=4), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_setting")),
    )
    op.create_index(op.f("ix_llm_setting_user_id"), "llm_setting", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_setting_user_id"), table_name="llm_setting")
    op.drop_table("llm_setting")
    # ### end Alembic commands ###
