"""external_sources

`external_source`(사용자가 등록한 조회 대상 사이트)와 `external_lookup_cache`(소스·제품별
최근 조회 결과, TTL 캐시)를 추가한다(Task 18).

Revision ID: 0008_external_sources
Revises: 0007_saved_views
Create Date: 2026-08-03 10:08:18.096535
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008_external_sources"
down_revision: str | None = "0007_saved_views"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_source",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("adapter_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("rate_limit_per_min", sa.Integer(), nullable=False),
        sa.Column("ttl_hours", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_external_source_category_id_category"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_source")),
        sa.UniqueConstraint("user_id", "name", name="uq_external_source_user_id_name"),
    )
    op.create_index(
        op.f("ix_external_source_user_id"), "external_source", ["user_id"], unique=False
    )
    op.create_index(
        "ix_external_source_user_id_category_id",
        "external_source",
        ["user_id", "category_id"],
        unique=False,
    )
    op.create_table(
        "external_lookup_cache",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("warning", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_external_lookup_cache_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["external_source.id"],
            name=op.f("fk_external_lookup_cache_source_id_external_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_lookup_cache")),
    )
    op.create_index(
        "ix_external_lookup_cache_source_id_product_id",
        "external_lookup_cache",
        ["source_id", "product_id", "fetched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_lookup_cache_user_id"),
        "external_lookup_cache",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_external_lookup_cache_user_id"), table_name="external_lookup_cache")
    op.drop_index(
        "ix_external_lookup_cache_source_id_product_id", table_name="external_lookup_cache"
    )
    op.drop_table("external_lookup_cache")
    op.drop_index("ix_external_source_user_id_category_id", table_name="external_source")
    op.drop_index(op.f("ix_external_source_user_id"), table_name="external_source")
    op.drop_table("external_source")
    # ### end Alembic commands ###
