"""external_source_probe

소스 하나에 실제로 조회를 시도한 기록을 담는 `external_source_probe` 를 추가한다
(Task 34 PR4). `external_lookup_cache` 는 성공한 조회만 담아 "이 소스가 언제부터
깨졌는지"를 알 방법이 없었다 — 이 테이블은 성공·실패를 가리지 않고 남기는 롤링 로그다.

Revision ID: 0010_external_source_probe
Revises: 0009_external_product_match
Create Date: 2026-08-20 08:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0010_external_source_probe"
down_revision: str | None = "0009_external_product_match"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_source_probe",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("warning", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["external_source.id"],
            name=op.f("fk_external_source_probe_source_id_external_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_source_probe")),
    )
    op.create_index(
        op.f("ix_external_source_probe_user_id"),
        "external_source_probe",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_external_source_probe_source_id_attempted_at",
        "external_source_probe",
        ["source_id", "attempted_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_external_source_probe_source_id_attempted_at", table_name="external_source_probe"
    )
    op.drop_index(op.f("ix_external_source_probe_user_id"), table_name="external_source_probe")
    op.drop_table("external_source_probe")
    # ### end Alembic commands ###
