"""source_presets_credentials

소스 프리셋 카탈로그 추적 컬럼(`preset_key`·`preset_version`·`spec_overridden`)을
`external_source` 에 추가하고, 소스별 자격 증명을 담는 `external_source_credential` 을
신설한다(Task 34 PR5).

Revision ID: 0011_source_presets_credentials
Revises: 0010_external_source_probe
Create Date: 2026-08-20 09:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011_source_presets_credentials"
down_revision: str | None = "0010_external_source_probe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("external_source", sa.Column("preset_key", sa.String(length=100), nullable=True))
    op.add_column("external_source", sa.Column("preset_version", sa.Integer(), nullable=True))
    # 기존 행을 모두 False 로 채우기 위해 server_default 를 잠깐 둔 뒤 지운다 — 모델은
    # Python 쪽 default 만 선언하므로, server_default 를 남겨 두면 드리프트로 잡힌다.
    op.add_column(
        "external_source",
        sa.Column("spec_overridden", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("external_source", "spec_overridden", server_default=None)

    op.create_table(
        "external_source_credential",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("secret_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("hint", sa.String(length=4), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["external_source.id"],
            name=op.f("fk_external_source_credential_source_id_external_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_source_credential")),
    )
    op.create_index(
        op.f("ix_external_source_credential_user_id"),
        "external_source_credential",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_external_source_credential_identity",
        "external_source_credential",
        ["source_id", "name"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_external_source_credential_identity",
        table_name="external_source_credential",
        postgresql_where="deleted_at IS NULL",
    )
    op.drop_index(
        op.f("ix_external_source_credential_user_id"), table_name="external_source_credential"
    )
    op.drop_table("external_source_credential")

    op.drop_column("external_source", "spec_overridden")
    op.drop_column("external_source", "preset_version")
    op.drop_column("external_source", "preset_key")
    # ### end Alembic commands ###
