"""llm_rematch

`llm_setting` 에 "LLM 매칭 보조" 토글(`rematch_enabled`)과 월 호출 상한
(`rematch_monthly_cap`)을 추가하고, 호출 비용 가드(24시간 dedup·월 상한 집계)에 쓸
`external_llm_rematch_log` 를 신설한다(Task 34 PR6).

Revision ID: 0012_llm_rematch
Revises: 0011_source_presets_credentials
Create Date: 2026-08-20 10:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0012_llm_rematch"
down_revision: str | None = "0011_source_presets_credentials"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_DEFAULT_REMATCH_MONTHLY_CAP = 200


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 행을 모두 채우기 위해 server_default 를 잠깐 둔 뒤 지운다 — 모델은 Python 쪽
    # default 만 선언하므로, server_default 를 남겨 두면 드리프트로 잡힌다(0011 과 동일
    # 패턴).
    op.add_column(
        "llm_setting",
        sa.Column("rematch_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("llm_setting", "rematch_enabled", server_default=None)
    op.add_column(
        "llm_setting",
        sa.Column(
            "rematch_monthly_cap",
            sa.Integer(),
            nullable=False,
            server_default=sa.text(str(_DEFAULT_REMATCH_MONTHLY_CAP)),
        ),
    )
    op.alter_column("llm_setting", "rematch_monthly_cap", server_default=None)

    op.create_table(
        "external_llm_rematch_log",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("called_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["external_source.id"],
            name=op.f("fk_external_llm_rematch_log_source_id_external_source"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_external_llm_rematch_log_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_llm_rematch_log")),
    )
    op.create_index(
        op.f("ix_external_llm_rematch_log_user_id"),
        "external_llm_rematch_log",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_external_llm_rematch_log_source_id_product_id_called_at",
        "external_llm_rematch_log",
        ["source_id", "product_id", "called_at"],
        unique=False,
    )
    op.create_index(
        "ix_external_llm_rematch_log_user_id_called_at",
        "external_llm_rematch_log",
        ["user_id", "called_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_external_llm_rematch_log_user_id_called_at", table_name="external_llm_rematch_log"
    )
    op.drop_index(
        "ix_external_llm_rematch_log_source_id_product_id_called_at",
        table_name="external_llm_rematch_log",
    )
    op.drop_index(
        op.f("ix_external_llm_rematch_log_user_id"), table_name="external_llm_rematch_log"
    )
    op.drop_table("external_llm_rematch_log")

    op.drop_column("llm_setting", "rematch_monthly_cap")
    op.drop_column("llm_setting", "rematch_enabled")
    # ### end Alembic commands ###
