"""관심 대상의 가격 감시·occurrence·논리 알림·푸시 전달과 암호화 구독.

Revision ID: 0018_price_watch
Revises: 0017_data_inventory

기존 관측·관심·구매 데이터는 변경하지 않는다. downgrade는 감시/알림 상태를 잃으므로
운영에서는 같은 이미지·스키마와 VAPID/암호화 키를 포함한 검증된 백업으로 복구한다.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0018_price_watch"
down_revision = "0017_data_inventory"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "push_subscription",
        sa.Column("endpoint_hash", sa.String(length=64), nullable=False),
        sa.Column("subscription_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("vapid_key_id", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_outcome", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_subscription")),
    )
    op.create_index(
        op.f("ix_push_subscription_user_id"), "push_subscription", ["user_id"], unique=False
    )
    op.create_index(
        "uq_push_subscription_endpoint",
        "push_subscription",
        ["endpoint_hash"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_table(
        "price_watch",
        sa.Column("interest_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("condition_key", sa.String(length=64), nullable=False),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("config_revision", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("schedule_enabled", sa.Boolean(), nullable=False),
        sa.Column("push_enabled", sa.Boolean(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("cooldown_seconds", sa.Integer(), nullable=False),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_outcome", sa.String(length=40), nullable=False),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_notified_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("last_satisfied", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("config_revision >= 1", name=op.f("ck_price_watch_positive_revision")),
        sa.CheckConstraint(
            "cooldown_seconds BETWEEN 900 AND 604800", name=op.f("ck_price_watch_bounded_cooldown")
        ),
        sa.CheckConstraint(
            "interval_seconds BETWEEN 900 AND 604800", name=op.f("ck_price_watch_bounded_interval")
        ),
        sa.ForeignKeyConstraint(
            ["interest_id"],
            ["interest.id"],
            name=op.f("fk_price_watch_interest_id_interest"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["external_source.id"],
            name=op.f("fk_price_watch_source_id_external_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_watch")),
    )
    op.create_index(
        "ix_price_watch_due",
        "price_watch",
        ["next_due_at"],
        unique=False,
        postgresql_where="deleted_at IS NULL AND is_active AND schedule_enabled",
    )
    op.create_index(op.f("ix_price_watch_user_id"), "price_watch", ["user_id"], unique=False)
    op.create_index(
        "uq_price_watch_condition",
        "price_watch",
        ["user_id", "interest_id", "source_id", "condition_key"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_table(
        "price_watch_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("watch_id", sa.UUID(), nullable=False),
        sa.Column("occurrence_key", sa.String(length=100), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("watch_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','running','succeeded','skipped','failed','cancelled')",
            name=op.f("ck_price_watch_run_valid_status"),
        ),
        sa.CheckConstraint(
            "attempts BETWEEN 0 AND 3", name=op.f("ck_price_watch_run_bounded_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["watch_id"],
            ["price_watch.id"],
            name=op.f("fk_price_watch_run_watch_id_price_watch"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_watch_run")),
        sa.UniqueConstraint("watch_id", "occurrence_key", name="uq_price_watch_occurrence"),
    )
    op.create_index(
        "ix_price_watch_run_queue", "price_watch_run", ["status", "available_at"], unique=False
    )
    op.create_index(
        op.f("ix_price_watch_run_user_id"), "price_watch_run", ["user_id"], unique=False
    )
    op.create_table(
        "price_notification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("watch_id", sa.UUID(), nullable=True),
        sa.Column("interest_id", sa.UUID(), nullable=True),
        sa.Column("observation_id", sa.UUID(), nullable=True),
        sa.Column("watch_revision", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["interest_id"],
            ["interest.id"],
            name=op.f("fk_price_notification_interest_id_interest"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["external_price_observation.id"],
            name=op.f("fk_price_notification_observation_id_external_price_observation"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["watch_id"],
            ["price_watch.id"],
            name=op.f("fk_price_notification_watch_id_price_watch"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_notification")),
        sa.UniqueConstraint("watch_id", "observation_id", name="uq_price_notification_observation"),
    )
    op.create_index(
        op.f("ix_price_notification_user_id"), "price_notification", ["user_id"], unique=False
    )
    op.create_table(
        "push_delivery",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("notification_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','sending','accepted','unknown','rejected',"
            "'expired','cancelled','blocked','queue_full')",
            name=op.f("ck_push_delivery_valid_status"),
        ),
        sa.CheckConstraint(
            "attempts BETWEEN 0 AND 3", name=op.f("ck_push_delivery_bounded_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["price_notification.id"],
            name=op.f("fk_push_delivery_notification_id_price_notification"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["push_subscription.id"],
            name=op.f("fk_push_delivery_subscription_id_push_subscription"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_delivery")),
        sa.UniqueConstraint("notification_id", "subscription_id", name="uq_push_delivery_event"),
    )
    op.create_index(
        "ix_push_delivery_queue", "push_delivery", ["status", "available_at"], unique=False
    )
    op.create_index(op.f("ix_push_delivery_user_id"), "push_delivery", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_push_delivery_user_id"), table_name="push_delivery")
    op.drop_index("ix_push_delivery_queue", table_name="push_delivery")
    op.drop_table("push_delivery")
    op.drop_index(op.f("ix_price_notification_user_id"), table_name="price_notification")
    op.drop_table("price_notification")
    op.drop_index(op.f("ix_price_watch_run_user_id"), table_name="price_watch_run")
    op.drop_index("ix_price_watch_run_queue", table_name="price_watch_run")
    op.drop_table("price_watch_run")
    op.drop_index(
        "uq_price_watch_condition", table_name="price_watch", postgresql_where="deleted_at IS NULL"
    )
    op.drop_index(op.f("ix_price_watch_user_id"), table_name="price_watch")
    op.drop_index(
        "ix_price_watch_due",
        table_name="price_watch",
        postgresql_where="deleted_at IS NULL AND is_active AND schedule_enabled",
    )
    op.drop_table("price_watch")
    op.drop_index(
        "uq_push_subscription_endpoint",
        table_name="push_subscription",
        postgresql_where="deleted_at IS NULL",
    )
    op.drop_index(op.f("ix_push_subscription_user_id"), table_name="push_subscription")
    op.drop_table("push_subscription")
    # ### end Alembic commands ###
